"""change column name from title to subject

Revision ID: 109fec7ba96d
Revises: faab23542412
Create Date: 2025-01-04 02:11:16.039927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '109fec7ba96d'
down_revision = 'faab23542412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
