"""Initial migration

Revision ID: 5a7fb19888f4
Revises: 3d8851d1618c
Create Date: 2025-01-04 01:47:32.149967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7fb19888f4'
down_revision = '3d8851d1618c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('courses_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('courses_ibfk_1', 'users', ['instructor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
