"""Initial migration

Revision ID: faab23542412
Revises: 5a7fb19888f4
Create Date: 2025-01-04 01:53:11.941431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faab23542412'
down_revision = '5a7fb19888f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('instructor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('instructor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
